<a href="https://colab.research.google.com/github/carlcodecode/Data-Science-II/blob/main/NNFromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

#this is our batch of data
N = 10
#data point will have one input and one output feature
D_in = 1
D_out = 1

X = torch.randn(N, D_in)

#create our "true labels" for training
W_true = torch.tensor([[2.0]])
b_true = torch.tensor(1.0)
y_true = X @ W_true + b_true + torch.randn(N, D_out) * 0.1 #add some noise

print(y_true[:])

tensor([[ 4.5807],
        [ 4.4269],
        [ 1.1115],
        [ 1.0987],
        [-0.1980],
        [-1.0085],
        [ 4.2295],
        [ 0.8105],
        [ 0.2932],
        [ 0.4800]])


In [ ]:
#initialize our parameters with random values
#shapes must be correct

W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f"Initial weight: {W}")
print(f"Initial b: {b}")

Initial weight: tensor([[-0.4030]], requires_grad=True)
Initial b: tensor([-0.8332], requires_grad=True)


In [ ]:
#forward pass
y_hat = X @ W + b
print(y_hat)
print(y_true)

tensor([[-1.5480],
        [-1.5673],
        [-0.9110],
        [-0.8544],
        [-0.6130],
        [-0.4199],
        [-1.4806],
        [-0.8187],
        [-0.6813],
        [-0.7301]], grad_fn=<AddBackward0>)
tensor([[ 4.5807],
        [ 4.4269],
        [ 1.1115],
        [ 1.0987],
        [-0.1980],
        [-1.0085],
        [ 4.2295],
        [ 0.8105],
        [ 0.2932],
        [ 0.4800]])


In [ ]:
# calculate loss
error = (y_hat - y_true)
squared_error = error ** 2
loss = squared_error.mean()
print(f"Our loss: {loss}")


Our loss: 11.959053039550781


In [ ]:
# backward pass + compute gradient using autograd
# calculate gradient of loss w.r.t. W
# calculate gradient of loss w.r.t. b

loss.backward()

print(f"Grad for W: {W.grad}")
print(f"Grad for b: {b.grad}")


Grad for W: tensor([[-6.2200]])
Grad for b: tensor([-5.0898])


In [ ]:
# update W and b
W = W - 0.1*W.grad
b = b - 0.1*b.grad

y_hat = X @ W + b

print(y_hat)

tensor([[ 0.0643],
        [ 0.0748],
        [-0.2819],
        [-0.3126],
        [-0.4439],
        [-0.5488],
        [ 0.0276],
        [-0.3321],
        [-0.4067],
        [-0.3802]], grad_fn=<AddBackward0>)


In [ ]:
# calculate loss
error = (y_hat - y_true)
squared_error = error ** 2
loss = squared_error.mean()
print(f"Our loss: {loss}")

Our loss: 6.373559474945068


In [28]:
#this is our batch of data
N = 10
#data point will have one input and one output feature
D_in = 1
D_out = 1

X = torch.randn(N, D_in)

#create our "true labels" for training
W_true = torch.tensor([[2.0]])
b_true = torch.tensor(1.0)
y_true = X @ W_true + b_true + torch.randn(N, D_out) * 0.1 #add some noise

print(y_true[:])

tensor([[-0.3054],
        [ 1.1211],
        [ 1.7664],
        [-2.1983],
        [ 2.0278],
        [ 1.4555],
        [ 2.0974],
        [ 4.1976],
        [ 2.7756],
        [ 1.1257]])


In [31]:
#training process

#hyper parameters
lr = 0.01
epochs = 100

W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

for epoch in range(epochs):
  #forward pass
  y_hat = X @ W + b
  #compute loss
  loss=torch.mean((y_hat-y_true)**2)
  #backward pass + compute gradients
  loss.backward()

  if epoch % 10 == 0:
    print(f"Epoch {epoch:02d}: Loss={loss.item():.4f}, W={W.item():.4f}, b={b.item():.4f}")

  #update params -> no_grad because we don't need to track the updates
  with torch.no_grad():
    W -= lr * W.grad
    b -= lr * b.grad

  #zero the gradients because we don't want to sum previous
  W.grad.zero_()
  b.grad.zero_()

print(f"Final Parameters: W={W.item():.4f}, b={b.item():.3f}")
print(f"True Parameters: W={W_true.item()}, b={b_true.item()}")



Epoch 00: Loss=17.1762, W=-0.6931, b=-1.9579
Epoch 10: Loss=11.0412, W=-0.2280, b=-1.3243
Epoch 20: Loss=7.1109, W=0.1522, b=-0.8230
Epoch 30: Loss=4.5901, W=0.4636, b=-0.4270
Epoch 40: Loss=2.9712, W=0.7193, b=-0.1145
Epoch 50: Loss=1.9298, W=0.9296, b=0.1317
Epoch 60: Loss=1.2585, W=1.1030, b=0.3254
Epoch 70: Loss=0.8248, W=1.2464, b=0.4774
Epoch 80: Loss=0.5437, W=1.3652, b=0.5966
Epoch 90: Loss=0.3610, W=1.4638, b=0.6897
Final Parameters: W=1.5460, b=0.762
True Parameters: W=2.0, b=1.0
